---
  - include_vars: main.yml
  - include_vars: esxi_drs.yml
  - include_vars: vm_details.yml
  - include_vars: vm_hardware.yml
  - include_vars: vmvault.yml
  # Create Vm from the below template
  - name: Create a VM from a template
    vmware_guest:
      hostname: '{{ vcenter_hostname }}'
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: '{{ item.vm_name }}'
      state: poweredon
      template: '{{ rhel_template }}'
      datacenter: '{{ datacenter_name }}'
      cluster: '{{ cluster }}'
      folder: "/{{ datacenter_name }}/vm/"
      hardware:
        memory_mb: '{{ ram }}'
        num_cpus: '{{ cpu }}'
        scsi: lsilogic
      disk:
      - size_gb: "{{ disk2_size }}"
        type: "{{ disk2_type }}"
        datastore: "{{ datastore_name }}"
        state: "{{ disk2_state }}"
      - size_gb: "{{ disk2_size }}"
        type: "{{ disk2_type }}"
        datastore: "{{ datastore_name }}"
        state: "{{ disk2_state }}"
      customization:
        hostname: '{{ item.hostname }}'
        autologon: yes
        password: '{{ vm_password }}'
        dns_servers:
        - 10.129.16.17
        - 10.129.16.18
      networks:
      - name: '{{ item.network_name }}'
        ip: '{{ item.addr }}'
        type: static
        netmask: '{{ netmask }}'
        gateway: '{{ gateway }}'
        domain: '{{ domain }}'
        connected: true
      - vlan: '{{ vlan }}'
        device_type: '{{ devicetype }}'
        dvswitch_name: '{{ dvswitch }}'
        wait_for_ip_address: yes
    delegate_to: localhost
    register: deploy
    with_items:
   #    - { vm_name: "{{ vm2_name }}", hostname: "{{ vm2_hostname }}", addr: "{{ vm2_ip }}", network_name: "{{ vm_network_name }}"  }
       - { vm_name: "{{ vm3_name }}", hostname: "{{ vm3_hostname }}", addr: "{{ vm3_ip }}", network_name: "{{ vm_network_name }}"  }
       - { vm_name: "{{ vm4_name }}", hostname: "{{ vm4_hostname }}", addr: "{{ vm4_ip }}", network_name: "{{ vm_network_name }}"  }
   #    - { vm_name: "{{ vm5_name }}", hostname: "{{ vm5_hostname }}", addr: "{{ vm5_ip }}", network_name: "{{ vm_network_name }}"  }


   


