---
    - include_vars: main.yml
    - include_tasks: new_machine_id.yml
    - name: Remove Swap
      command: swapoff -a
    
    - name: Remove Yum proxy settings
      lineinfile:
        path: /etc/yum.conf
        state: absent
        regexp: '^proxy'

   
    - name: setup docker
      import_tasks: docker-set-up.yml
    
    - name: Install epel
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present

    - name: Disable the EPEL repository globally 
      command: sed -i -e "s/^enabled=1/enabled=0/" /etc/yum.repos.d/epel.repo

    - name: Install a list of packages
      yum:
        name:
         - wget
         - git
         - net-tools
         - bind-utils
         - yum-utils
         - iptables-services
         - bridge-utils
         - bash-completion
         - sos
         - psacct
         - dnsmasq
         - pyOpenSSL

        state: present

    - name: now update the node
      yum:
        name: "*"
        exclude: ansible*
        state: latest

   
    - name: Install Ansible
      yum:
        name: https://releases.ansible.com/ansible/rpm/release/epel-7-x86_64/ansible-2.6.5-1.el7.ans.noarch.rpm
        state: installed

    - name: check for git repo already installed
      stat:
        path: /root/OKD/OKD_Install
      register: git

    - name: Download and install openshift-ansible
      git:
        repo: 'https://github.com/openshift/openshift-ansible.git'
        dest: /root/OKD/OKD_Install
        version: release-3.11
      become: yes
      when: git.stat.exists == False

    
    - name: Create DNSMASQ Conf file
      template:
        src: okd.j2
        dest: "/etc/dnsmasq.d/okd.conf"  

    - name: copy new resolv to upstream
      copy:
        src: /etc/resolv.conf
        dest: /etc/resolv.conf.upstream
        remote_src: yes
      backup: yes

    - name: Create a new and correctected resolv.conf file
      template:
        src: resolv.j2
        dest: "/etc/resolv.conf"
      

    - name: Set up directory for git clone
      file:
        path: /root/OKD
        state: directory
        mode: '0755'
          
    - name: copy over OKD Inventory File
      copy:
        src:  hosts_aio2
        dest: /root/OKD/
        mode: '0755'

    - name: Make sure gateway is configured
      lineinfile:
         path: /etc/sysconfig/network-scripts/ifcfg-ens192
         state: present
         regexp: '^GATEWAY'
         insertafter: '^NAME'
         line: 'GATEWAY=10.60.10.1'
    
    - name: Network Peers no
      lineinfile:
         path: /etc/sysconfig/network-scripts/ifcfg-ens192
         state: present
         regexp: '^PEERSDNS'
         line: 'PEERSDNS=no'

    - name: set hostname
      hostname:
        name: "{{ ansible_hostname }}"

    - name: prepare static routing
      copy:
        src: route-ens192
        dest: /etc/sysconfig/network-scripts/route-ens192

    - name: restart networking 
      service:
        name: network
        state: restarted
      async: 120
      poll: 0
           
    - name: Wait for system to become reachable
      wait_for_connection:

    - name: Remove no-resolve from origin-dns.conf
      lineinfile:
        path: /root/OKD/OKD_Install/roles/openshift_node/templates/origin-dns.conf.j2
        regexp: '^no-resolv'
        line: '#no-resolve'
        state: present
       
    - name: restart dnsmasq
      service:
        name: dnsmasq
        state: running
        enabled: yes

    - name: remove uneeded netwok interface
      file:
        path: /etc/sysconfig/network-scripts/ifcfg-ens224
        state: absent
   
    - name: Create a new and correctected resolv.conf file
      template:
        src: resolv.j2
        dest: "/etc/resolv.conf"
      backup: yes