---
    - name: Remove Swap
      command: swapoff -a
    
    - name: Remove Yum proxy settings
      lineinfile:
        path: /etc/yum.conf
        state: absent
        regexp: '^proxy'

   
    - name: setup docker
      import_tasks: docker-set-up.yml
    
    - name: Install epel
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present

    - name: Disable the EPEL repository globally 
      command: sed -i -e "s/^enabled=1/enabled=0/" /etc/yum.repos.d/epel.repo

    - name: Install a list of packages
      yum:
        name:
         - wget
         - git
         - net-tools
         - bind-utils
         - yum-utils
         - iptables-services
         - bridge-utils
         - bash-completion
         - sos
         - psacct
         - dnsmasq
         - pyOpenSSL

      state: present

    - name: now update the node
      yum:
        name: "*"
        exclude: ansible*
        state: latest

   
    - name: Install Ansible
      yum:
        name: https://releases.ansible.com/ansible/rpm/release/epel-7-x86_64/ansible-2.6.5-1.el7.ans.noarch.rpm
        state: installed

    #- name: Install Openshift-Ansible Playbooks
    #  yum:
    #    name: openshift-ansible
    #    state: installed

    
    - name: Create DNSMASQ Conf file
      copy:
        dest: "/etc/dnsmasq.d/okd.conf"
        content: |
          address=/.uat.okd.insurance.lan/10.60.10.27
          resolv-file=/etc/resolv.conf.upstream

    - name: copy new resolv to upstream
      copy:
        src: /etc/resolv.conf
        dest: /etc/resolve.conf.upstream
        remote_src: yes

    - name: set hostname
      hostname:
        name: master

    - name: Set up directory for git clone
      file:
        path: /root/OKD
        state: directory
        mode: '0755'

    - name: Download and install openshift-ansible
      git:
        repo: 'https://github.com/openshift/openshift-ansible.git'
        dest: /root/OKD/
        version: release-3.11
      become: yes
                
    - name: copy over OKD Inventory File
      copy:
        src:  hosts_aio2
        dest: /root/OKD/
        mode: '0755'

    - name: Copy resolve.conf to Upstream
      copy:
        src: /etc/resolv.conf
        dest: /etc/resolv.con.upstrem
        remote_src: yes

    - name: Remove no-resolve from origin-dns.conf
      lineinfile:
        path: /root/OKD/roles/openshift_node/templates/origin-dns.conf.j2
        regexp: '^no-resolv'
        line: '#no-resolve'
        state: present



